export const Properties = {
  API_URL: 'http://10.0.2.2:8000/',
  AUTH_COOKIE_DOMAIN: 'http://10.0.2.2/auth',
  NAVER_APP_NAME: 'YOUR-APP-NAME',
  NAVER_CONSUMER_KEY: 'YOUR-CONSUMER-KEY',
  NAVER_CONSUMER_SECRET: 'YOUR-CONSUMER-SECRET',
  NAVER_URL_SCHEME: 'YOUR-URL-SCHEME',
};
